Repository puppetlabs/puppetlabs-concat, pull requests merged in 2018-11, with the labels that each got.

#519 (MODULES-5124) Add support for JSON arrays
  README.md
  lib/puppet/type/concat_file.rb
  manifests/init.pp
  spec/acceptance/format_spec.rb
  spec/unit/type/concat_file_spec.rb
Labels: feature

#532 (maint) - Normalise Windows OS Names
  metadata.json
Labels: maintenance

#534 (FM-7513) - Removing Windows 2016-core from our support matrix
  metadata.json
Labels: bugfix

#535 (MODULES-8287) - Fix fomat=>'yaml' allowing only hashes
  lib/puppet/type/concat_file.rb
  spec/acceptance/format_spec.rb
Labels: bugfix
