Repository puppetlabs/puppetlabs-concat, pull requests merged in 2018-10, with the labels that each got.

#525 pdksync - (FM-7392) - Puppet 6 Testing Changes
  .rubocop.yml
  .travis.yml
  Gemfile
  appveyor.yml
  metadata.json
  spec/default_facts.yml
Labels: feature

#529 Release merge back 5.1.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#517 (MODULES-7717) ensure_newline uses unix line ending on windows
  lib/puppet/type/concat_file.rb
  spec/acceptance/newline_spec.rb
Labels: bugfix

#531 (MODULES-8088) - newline_spec.rb test expectation update
  spec/acceptance/newline_spec.rb
Labels: bugfix
