Repository puppetlabs/puppetlabs-concat, pull requests merged in 2019-05, with the labels that each got.

#578 (MODULES-9017) - update metadata to support current version of stdlib
  metadata.json
Labels: maintenance

#577 (FM-7606) enable litmus for concat
  .fixtures.yml
  .sync.yml
  .travis.yml
  Gemfile
  README.md
  Rakefile
  appveyor.yml
  distelli-manifest.yml
  metadata.json
  provision.yaml
  spec/acceptance/backup_spec.rb
  spec/acceptance/concat_spec.rb
  spec/acceptance/concurrency_spec.rb
  spec/acceptance/force_spec.rb
  spec/acceptance/format_spec.rb
  spec/acceptance/fragment_order_spec.rb
  spec/acceptance/fragment_replace_spec.rb
  spec/acceptance/fragment_source_spec.rb
  spec/acceptance/fragments_are_always_replaced_spec.rb
  spec/acceptance/locales_spec.rb
  spec/acceptance/newline_spec.rb
  spec/acceptance/noop_spec.rb
  spec/acceptance/order_spec.rb
  spec/acceptance/pup_1963_spec.rb
  spec/acceptance/quoted_paths_spec.rb
  spec/acceptance/symbolic_name_spec.rb
  spec/acceptance/validation_spec.rb
  spec/acceptance/warn_header_spec.rb
  spec/acceptance/warnings_spec.rb
  spec/spec_helper_acceptance.rb
  spec/spec_helper_acceptance_local.rb
Labels: feature

#580 (FM-8073) litmus block support
  spec/acceptance/backup_spec.rb
  spec/acceptance/force_spec.rb
  spec/acceptance/fragment_replace_spec.rb
  spec/acceptance/fragment_source_spec.rb
  spec/acceptance/locales_spec.rb
  spec/acceptance/pup_1963_spec.rb
  spec/acceptance/warnings_spec.rb
Labels: bugfix

#582 (MODULES-9109) Release mergeback v6.0.0
  CHANGELOG.md
  metadata.json
Labels: maintenance

#586 (maint) exit if travis setup fails
  .travis.yml
Labels: maintenance
