Repository puppetlabs/puppetlabs-concat, pull requests merged in 2019-11, with the labels that each got.

#610 pdksync - (FM-8634) ensure encrypted communication for fixtures
  .fixtures.yml
Labels: maintenance

#613 pdksync - FM-8499 - remove ubuntu14 support
  metadata.json
  provision.yaml
Labels: backwards-incompatible

#615 (FM-8698) - Addition of Support for CentOS 8
  metadata.json
  provision.yaml
Labels: feature

#616 (MODULES-10120) enable simplecov; update to PDK 1.14.1; minor cleanups
  .gitignore
  .pdkignore
  .project
  .sync.yml
  .travis.yml
  appveyor.yml
  metadata.json
Labels: maintenance
