Repository puppetlabs/puppetlabs-concat, pull requests merged in 2019-01, with the labels that each got.

#552 pdksync - pdksync_heads/master-0-g9c815ea
  .travis.yml
  metadata.json
  spec/acceptance/locales_spec.rb
Labels: maintenance

#562 pdksync - pdksync_1.9.0-0-g7281db5
  .puppet-lint.rc
  metadata.json
  spec/spec_helper.rb
Labels: maintenance

#559 (FM-7724) - Remove Windows 8 testing/support
  metadata.json
Labels: backwards-incompatible

#560 (FM-7720/FM-7722/FM-7723) Consolidate Windows Metadata
  metadata.json
Labels: bugfix
