Repository puppetlabs/puppetlabs-concat, pull requests merged in 2020-01, with the labels that each got.

#619 pdksync - (maint) travis updates: bundler and slack
  .sync.yml
  .travis.yml
  metadata.json
Labels: maintenance

#623 Fix newline handling at the end of fragments
  lib/puppet/type/concat_file.rb
Labels: bugfix

#624 pdksync - (FM-8581) - Debian 10 added to travis and provision file refactored
  .sync.yml
  .travis.yml
  provision.yaml
Labels: feature

#621 pdksync - FM-8834 - Add GitHub action workflow
  .github/workflows/release.yml
Labels: maintenance
