Repository puppetlabs/puppetlabs-concat, pull requests merged in 2023-03, with the labels that each got.

#755 (MODULES-3522) Removing redundant 'requires'
  lib/puppet/type/concat_file.rb
Labels: bugfix

#759 Revert "(MODULES-3522) Removing redundant 'requires'"
  lib/puppet/type/concat_file.rb
Labels: bugfix

#761 puppet5: drop remnants of puppet5 code
  manifests/fragment.pp
Labels: community

#763 pdksync - (CONT-768) Pin puppetlabs-puppet_agent
  .fixtures.yml
Labels: maintenance

#765 pdksync - CONT-826/main/pin_puppet_litmus
  Gemfile
Labels: maintenance
