Repository puppetlabs/puppetlabs-concat, pull requests merged in 2023-04, with the labels that each got.

#767 pdksync - (CONT-844) - Update .sync.yml
  .sync.yml
Labels: maintenance

#768 (CONT-775) Puppet 8 support
  .fixtures.yml
  .rubocop.yml
  .rubocop_todo.yml
  Gemfile
  README.md
  Rakefile
  lib/puppet/type/concat_file.rb
  lib/puppet/type/concat_fragment.rb
  manifests/init.pp
  metadata.json
  spec/acceptance/backup_spec.rb
  spec/acceptance/fragment_replace_spec.rb
  spec/acceptance/fragments_are_always_replaced_spec.rb
  spec/acceptance/newline_spec.rb
  spec/acceptance/noop_spec.rb
  spec/acceptance/warn_header_spec.rb
  spec/acceptance/warnings_spec.rb
  spec/defines/concat_fragment_spec.rb
  spec/defines/concat_spec.rb
  spec/spec_helper.rb
  spec/spec_helper_local.rb
  spec/unit/type/concat_file_spec.rb
  spec/unit/type/concat_fragment_spec.rb
Labels: backwards-incompatible

#773 (CONT-874) Update changelog to address wrong title
  CHANGELOG.md
Labels: maintenance

#774 (CONT-891) Address nightly rubocop failures
  .rubocop_todo.yml
  spec/acceptance/fragments_are_always_replaced_spec.rb
Labels: bugfix
